"""empty message

Revision ID: 10959a9b173a
Revises: 75cf10f911cf
Create Date: 2024-06-21 21:20:33.029086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10959a9b173a'
down_revision = '75cf10f911cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label1', sa.String(length=100), nullable=True),
    sa.Column('label2', sa.String(length=100), nullable=True),
    sa.Column('html_header', sa.Text(), nullable=True),
    sa.Column('html_zone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_page')
    # ### end Alembic commands ###
