"""empty message

Revision ID: 110bfcd6bf36
Revises: d247170f1fae
Create Date: 2024-06-19 15:37:21.293663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110bfcd6bf36'
down_revision = 'd247170f1fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('img', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('img')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
