"""empty message

Revision ID: 377a9d003cf0
Revises: 3e9a93415821
Create Date: 2024-06-20 01:08:57.718824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a9d003cf0'
down_revision = '3e9a93415821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_html', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.drop_column('header_html')

    # ### end Alembic commands ###
