"""empty message

Revision ID: 3e9a93415821
Revises: ed920cbce672
Create Date: 2024-06-19 23:07:57.317410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9a93415821'
down_revision = 'ed920cbce672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
