"""empty message

Revision ID: 490706077f3b
Revises: 77c58121abb6
Create Date: 2024-06-19 00:53:23.233708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490706077f3b'
down_revision = '77c58121abb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baners')
    # ### end Alembic commands ###
