"""empty message

Revision ID: 75cf10f911cf
Revises: 377a9d003cf0
Create Date: 2024-06-20 02:00:10.073774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cf10f911cf'
down_revision = '377a9d003cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_html', sa.String(length=300), nullable=True))

    with op.batch_alter_table('kv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_html', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kv', schema=None) as batch_op:
        batch_op.drop_column('header_html')

    with op.batch_alter_table('home', schema=None) as batch_op:
        batch_op.drop_column('header_html')

    # ### end Alembic commands ###
