"""empty message

Revision ID: 77c58121abb6
Revises: 83bfc3c5fdd0
Create Date: 2024-06-19 00:31:48.138656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c58121abb6'
down_revision = '83bfc3c5fdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('busines', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
