"""empty message

Revision ID: 942b35a8d0fc
Revises: 0fef2ba77ae0
Create Date: 2024-06-22 17:41:51.700925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942b35a8d0fc'
down_revision = '0fef2ba77ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
