"""empty message

Revision ID: d247170f1fae
Revises: 7ca7854adf74
Create Date: 2024-06-19 02:59:42.246735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd247170f1fae'
down_revision = '7ca7854adf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_baner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('check1', sa.String(length=100), nullable=True),
    sa.Column('check2', sa.String(length=100), nullable=True),
    sa.Column('check3', sa.String(length=100), nullable=True),
    sa.Column('check4', sa.String(length=100), nullable=True),
    sa.Column('label_tarif', sa.String(length=100), nullable=True),
    sa.Column('label_zone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_baner')
    # ### end Alembic commands ###
