"""empty message

Revision ID: eaaaca255142
Revises: 
Create Date: 2024-06-16 22:58:08.028085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaaca255142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('base_url', sa.String(length=150), nullable=True),
    sa.Column('metrica_html', sa.String(length=300), nullable=True),
    sa.Column('zone_html', sa.String(length=300), nullable=True),
    sa.Column('tariffs', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kv')
    # ### end Alembic commands ###
